baseURL = "https://docs.vectorcharts.com/"
languageCode = "en-us"
title = "VectorCharts Documentation"
theme = "docs-theme"
pluralizelisttitles = false

[markup.goldmark.renderer]
unsafe = true

[params]
    version = "v0.1.0"
    siteUrl = "http://localhost:1313"
    docsUrl = "http://localhost:1313"
    filesUrl = "http://localhost:1313"

[menu]
    [[menu.main]]
        identifier = "getting_started"
        title = "Getting Started"
        pre = "<span class='bp3-icon bp3-icon-learning'></span>"
        weight = 1
    [[menu.main]]
        identifier = "api_reference"
        title = "Core API Reference"
        pre = "<span class='bp3-icon bp3-icon-code'></span>"
        weight = 2
    [[menu.main]]
        identifier = "chart_api_reference"
        title = "Chart API Reference"
        pre = "<span class='bp3-icon bp3-icon-map'></span>"
        weight = 3
    [[menu.main]]
        identifier = "examples"
        title = "Examples"
        pre = "<span class='bp3-icon bp3-icon-learning'></span>"
        weight = 4
    [[menu.oem]]
        identifier = "getting_started"
        title = "Getting Started"
        pre = "<span class='bp3-icon bp3-icon-learning'></span>"
        weight = 1
    [[menu.oem]]
        identifier = "api_reference"
        title = "API Reference"
        pre = "<span class='bp3-icon bp3-icon-code'></span>"
        weight = 2
    [[menu.oem]]
        identifier = "examples"
        title = "Examples"
        pre = "<span class='bp3-icon bp3-icon-learning'></span>"
        weight = 3